# ==========================================
# Application Identity
# ==========================================
spring.application.name=decision-engine-service

server.port=${PORT:7002}

# ==========================================
# Config Server
# ==========================================
spring.config.import=configserver:https://config-server-7jdt.onrender.com
spring.cloud.config.profile=dev
spring.cloud.config.fail-fast=true

spring.cloud.config.retry.max-attempts=5
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=5000
spring.cloud.config.retry.multiplier=1.5

# ==========================================
# Google Gemini API Key
# ==========================================
google.api.key=${GOOGLE_API_KEY}

# ==========================================
# Eureka Client
# ==========================================
eureka.client.service-url.defaultZone=https://eureka-server-ku09.onrender.com/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# ==========================================
# Logging
# ==========================================
logging.level.root=INFO
logging.level.com.cts.gemini_test_try2=DEBUG