# ==========================================
# Application Identity
# ==========================================
spring.application.name=transactionService
server.port=8089

# ==========================================
# Config Server
# ==========================================
spring.config.import=configserver:http://config-server:8888
spring.cloud.config.profile=dev
spring.cloud.config.fail-fast=true

# ==========================================
# Eureka Client
# ==========================================
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# ==========================================
# Actuator (optional)
# ==========================================
#management.endpoints.web.exposure.include=health,info
#management.endpoint.health.show-details=always

# ==========================================
# Application Info
# ==========================================
#info.app.name=Transaction Service
#info.app.description=This service provides functionality for managing user accounts.
#info.app.version=1.0.0