# ==========================================
# Application Identity
# ==========================================
spring.application.name=transactionService

# Render dynamic port
server.port=${PORT:8089}

# ==========================================
# Config Server
# ==========================================
spring.config.import=configserver:https://config-server-7jdt.onrender.com
spring.cloud.config.profile=dev
spring.cloud.config.fail-fast=true

# Retry Config Server connection
spring.cloud.config.retry.max-attempts=5
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=5000
spring.cloud.config.retry.multiplier=1.5

# ==========================================
# Eureka Client
# (will be overridden by Config Server)
# ==========================================
eureka.client.service-url.defaultZone=https://eureka-server-ku09.onrender.com/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# ==========================================
# Actuator (Optional)
# ==========================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ==========================================
# Application Info
# ==========================================
info.app.name=Transaction Service
info.app.description=Used to initiate and manage transactions
info.app.version=1.0.0