spring:
  application:
    name: alert-case-service

  config:
    import: configserver:https://config-server-7jdt.onrender.com

  cloud:
    config:
      profile: dev
      fail-fast: false

server:
  port: ${PORT:8085}

eureka:
  client:
    service-url:
      defaultZone: https://eureka-server-ku09.onrender.com/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

brevo:
  api-key: ${BREVO_API_KEY}
  from: ${BREVO_FROM:bunnypraveen70@gmail.com}
  from-name: ${BREVO_FROM_NAME:BankGuard}
  api-url: ${BREVO_API_URL:https://api.brevo.com/v3/smtp/email}