# ==========================================
# Application Identity
# ==========================================
spring.application.name=enrichmentService
server.port=8010

# ==========================================
# Config Server
# ==========================================
spring.config.import=configserver:http://config-server:8888
spring.cloud.config.profile=dev
spring.cloud.config.fail-fast=true

# ==========================================
# Eureka Client
# ==========================================
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# ==========================================
# Logging
# ==========================================
logging.level.root=INFO
logging.level.com.bankguard.enrichmentservice=DEBUG

# ==========================================
# External Service URLs
# ==========================================
external.alertcase-service.url=http://alert-case-service:8085