# ==========================================
# Application Identity
# ==========================================
spring.application.name=sarReport

server.port=${PORT:8088}

# ==========================================
# Config Server
# ==========================================
spring.config.import=optional:configserver:https://config-server-7jdt.onrender.com
spring.cloud.config.profile=dev
spring.cloud.config.fail-fast=false

spring.cloud.config.retry.max-attempts=5
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=5000
spring.cloud.config.retry.multiplier=1.5

# ==========================================
# Eureka Client
# ==========================================
eureka.client.service-url.defaultZone=https://eureka-server-ku09.onrender.com/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# ==========================================
# Swagger
# ==========================================
# springdoc.swagger-ui.path=/swagger-ui.html
# springdoc.api-docs.path=/v3/api-docs