# ==========================================
# Application Identity
# ==========================================
spring.application.name=apiGateway
server.port=${PORT:1001}

# Required for Spring Cloud Gateway
spring.main.web-application-type=reactive

# ==========================================
# Config Server
# ==========================================
spring.config.import=optional:configserver:https://config-server-7jdt.onrender.com
spring.cloud.config.profile=dev
spring.cloud.config.fail-fast=false

spring.cloud.config.retry.max-attempts=10
spring.cloud.config.retry.initial-interval=3000
spring.cloud.config.retry.max-interval=10000
spring.cloud.config.retry.multiplier=1.5

# ==========================================
# Eureka
# ==========================================
eureka.client.service-url.defaultZone=https://eureka-server-ku09.onrender.com/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# ==========================================
# JWT
# ==========================================
jwt.secret=BankGuardSuperSecretKeyForJWT2025ThisMustBeLongEnoughForHS256Algorithm
jwt.expiration=86400000