# ==========================================
# Application Identity
# ==========================================
spring.application.name=apiGateway
server.port=${PORT:1001}

# Force reactive mode (required for Spring Cloud Gateway)
spring.main.web-application-type=reactive

# ==========================================
# Config Server
# ==========================================
spring.config.import=configserver:https://config-server-7jdt.onrender.com
spring.cloud.config.profile=dev

spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=5
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=5000
spring.cloud.config.retry.multiplier=1.5

# ==========================================
# Database (Docker MySQL Container)
# ==========================================
spring.r2dbc.url=r2dbc:mysql://thomas.proxy.rlwy.net:40415/bankguard_auth
spring.r2dbc.username=root
spring.r2dbc.password=${MYSQL_PASSWORD}

# ==========================================
# Eureka Server
# ==========================================
eureka.client.service-url.defaultZone=https://eureka-server-ku09.onrender.com/eureka/
eureka.instance.prefer-ip-address=true

# ==========================================
# JWT Secret
# ==========================================
jwt.secret=BankGuardSuperSecretKeyForJWT2025ThisMustBeLongEnoughForHS256Algorithm
jwt.expiration=86400000