# ==========================================
# Application Identity
# ==========================================
spring.application.name=apiGateway
server.port=1001

# Force reactive mode (required for Spring Cloud Gateway)
spring.main.web-application-type=reactive

# ==========================================
# Config Server
# ==========================================
spring.config.import=configserver:http://config-server:8888
spring.cloud.config.profile=dev

spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=5
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=5000
spring.cloud.config.retry.multiplier=1.5

# ==========================================
# Database (Docker MySQL Container)
# ==========================================
spring.r2dbc.url=r2dbc:mysql://mysql:3306/bankguard_auth
spring.r2dbc.username=root
spring.r2dbc.password=root

# ==========================================
# Eureka Server
# ==========================================
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

# ==========================================
# JWT Secret
# ==========================================
jwt.secret=BankGuardSuperSecretKeyForJWT2025ThisMustBeLongEnoughForHS256Algorithm
jwt.expiration=86400000